package com.author.blank_mixin_mod.autotierlist.event;

import com.author.blank_mixin_mod.autotierlist.command.AutoTierlistClientCommand;
import com.author.blank_mixin_mod.autotierlist.config.AutoTierlistConfig;
import com.author.blank_mixin_mod.autotierlist.generation.TierlistGenerator;
import com.author.blank_mixin_mod.autotierlist.integration.EMIIntegration;
import com.mojang.logging.LogUtils;
import net.minecraft.client.Minecraft;
import net.minecraft.client.multiplayer.ClientLevel;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.client.event.RegisterClientCommandsEvent;
import net.minecraftforge.event.level.LevelEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import org.slf4j.Logger;

/**
 * Handles client lifecycle events for Auto-Tierlist.
 */
@Mod.EventBusSubscriber(modid = "blank_mixin_mod", bus = Mod.EventBusSubscriber.Bus.FORGE, value = Dist.CLIENT)
public class ClientEventHandler {
    private static final Logger LOGGER = LogUtils.getLogger();
    private static boolean hasAutoGenerated = false;

    /**
     * Register client commands.
     */
    @SubscribeEvent
    public static void onRegisterClientCommands(RegisterClientCommandsEvent event) {
        AutoTierlistClientCommand.register(event.getDispatcher());
        LOGGER.info("Auto-Tierlist client commands registered");
    }

    /**
     * Auto-generate tierlists when a world loads (if enabled in config).
     * This triggers when joining a single-player world or connecting to a server.
     */
    @SubscribeEvent
    public static void onWorldLoad(LevelEvent.Load event) {
        // Only run on client side and for the client level
        if (event.getLevel().isClientSide() && event.getLevel() instanceof ClientLevel) {
            Minecraft mc = Minecraft.getInstance();

            // Check if we're in single-player with an integrated server
            if (mc.hasSingleplayerServer() && mc.getSingleplayerServer() != null && !hasAutoGenerated) {
                hasAutoGenerated = true;

                // Schedule generation on server thread to ensure all mods are loaded
                mc.getSingleplayerServer().execute(() -> {
                    if (AutoTierlistConfig.autoGenerateOnStart) {
                        LOGGER.info("Auto-generating tierlists on world load...");
                        try {
                            // Initialize EMI integration
                            EMIIntegration.initialize();

                            TierlistGenerator generator = new TierlistGenerator();
                            generator.generateAll(mc.getSingleplayerServer());
                        } catch (Exception e) {
                            LOGGER.error("Failed to auto-generate tierlists on world load", e);
                        }
                    } else {
                        LOGGER.info("Auto-generation on world load is disabled in config");
                        LOGGER.info("Use '/autotierlist generate' to manually generate tierlists");
                    }
                });
            }
        }
    }

    /**
     * Reset auto-generation flag when world unloads.
     */
    @SubscribeEvent
    public static void onWorldUnload(LevelEvent.Unload event) {
        if (event.getLevel().isClientSide() && event.getLevel() instanceof ClientLevel) {
            hasAutoGenerated = false;
        }
    }
}
